#!/bin/bash


export TAG=$(make docker.tag)
export IMAGE=$(make docker.imagename)

# Build docker image
make docker.build

# Load docker image into local kind cluster
#kind load docker-image $IMAGE:$TAG --name external-secrets
k3d image import $IMAGE:$TAG -c passbolt-external-secrets

# (Optional) Pull the image from GitHub Repo to copy into kind
# docker pull ghcr.io/external-secrets/external-secrets:v0.8.2
# kind load docker-image ghcr.io/external-secrets/external-secrets:v0.8.2 -n external-secrets
# export TAG=v0.8.2
helm uninstall external-secrets

# Update helm charts and install to KinD cluster
make helm.generate
helm upgrade --install external-secrets ./deploy/charts/external-secrets/ \
--set image.repository=$IMAGE --set image.tag=$TAG \
--set webhook.image.repository=$IMAGE --set webhook.image.tag=$TAG \
--set certController.image.repository=$IMAGE --set certController.image.tag=$TAG

kubectl rollout status -w deployment external-secrets
kubectl rollout status -w deployment external-secrets-webhook
kubectl rollout status -w deployment external-secrets-cert-controller

kubectl apply -k external-secrets-test

