apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: passbolt-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: passbolt
    kind: SecretStore
  target:
    name: example-passbolt-sync
  dataFrom:
    - find:
        name:
          regexp: ".*"
  data:
  - secretKey: name_a
    remoteRef:
      key: 8f291cda-d90a-4180-823b-d738622ef359
      property: name
